version: '3'

services:
  app:
    image: gyezhov266/project1:latest
    container_name: project1
    ports:
      - 8080:8080
    environment:
      - VARIABLE=VALUE
    volumes:
      - ./logs/:/logs/
  
  loki:
    image: grafana/loki:latest
    container_name: loki-logging
    ports:
      - 3100:3100

  promtail:
    image: grafana/promtail:latest
    container_name: promtail-logging
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./logs/staticLogs.log:/var/log/staticLogs.log
    command: "--config.file=/etc/promtail/promtail-config.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-logging
    # volumes:
    #   - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - loki