groups:
- name: example
  rules:

  - alert: APIHighLatency:5min
    expr: sum(rate(http_server_requests_seconds_sum{job="project1"}[5m])) / sum(rate(http_server_requests_seconds_count{job="project1"}[5m])) > 0.2
    labels:
      severity: warn
    annotations:
      summary: "5min latency too high"
      description: "Project1 is taking too long to handle requests in a 5-minute range"